apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-service-deployment
  namespace: library-service-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-service
  template:
    metadata:
      labels:
        app: library-service
    spec:
      containers:
        - name: library-service-container
          image: library-service-image
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          ports:
            - containerPort: 8100
