apiVersion: v1
kind: Service
metadata:
  name: library-service-service
  namespace: library-service-namespace
spec:
  type: NodePort
  selector:
    app: library-service
  ports:
    - port: 8100          # container's port
      targetPort: 8100
      nodePort: 30082     # exposed externally on localhost
